version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "bento"
    ports:
      - "15432:5432"
    volumes:
      - bento:/var/lib/postgres

#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_USER: root
#      MYSQL_ROOT_PASSWORD: saga
#    volumes:
#      - bento:/var/lib/mysql

volumes:
  bento:
